spring.application.name=order-service
server.port=8080

logging.level.root=DEBUG

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest


order.validation.stock.queue=q.stock.validation
order.validation.discount.queue=q.discount.validation
order.validation.exchange=x.order.validation
