spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest


order.validation.stock.queue=q.stock.validation
order.validation.discount.queue=q.discount.validation
# fanout
order.validation.exchange=x.order.validation

order.validation.response.queue=q.validation.response
# fanout
order.validation.response.exchange=x.validation.response
